package com.jwh.entity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aid
     *
     * @mbg.generated Mon Apr 06 20:31:00 CST 2020
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aname
     *
     * @mbg.generated Mon Apr 06 20:31:00 CST 2020
     */
    private String aname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.apwd
     *
     * @mbg.generated Mon Apr 06 20:31:00 CST 2020
     */
    private String apwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aid
     *
     * @return the value of admin.aid
     *
     * @mbg.generated Mon Apr 06 20:31:00 CST 2020
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aid
     *
     * @param aid the value for admin.aid
     *
     * @mbg.generated Mon Apr 06 20:31:00 CST 2020
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aname
     *
     * @return the value of admin.aname
     *
     * @mbg.generated Mon Apr 06 20:31:00 CST 2020
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aname
     *
     * @param aname the value for admin.aname
     *
     * @mbg.generated Mon Apr 06 20:31:00 CST 2020
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.apwd
     *
     * @return the value of admin.apwd
     *
     * @mbg.generated Mon Apr 06 20:31:00 CST 2020
     */
    public String getApwd() {
        return apwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.apwd
     *
     * @param apwd the value for admin.apwd
     *
     * @mbg.generated Mon Apr 06 20:31:00 CST 2020
     */
    public void setApwd(String apwd) {

        this.apwd = apwd == null ? null : apwd.trim();
    }

    @Override
    public String toString() {
        return "Admin{" +
                "aid=" + aid +
                ", aname='" + aname + '\'' +
                ", apwd='" + apwd + '\'' +
                '}';
    }
}